config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :product_types
  resources :products
  resources :notes
  resources :note_categories
  resources :brands

  root 'static_pages#home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: %i[ show edit update destroy ]

  # GET /product_types or /product_types.json
  def index
    @product_types = ProductType.all
  end

  # GET /product_types/1 or /product_types/1.json
  def show
  end

  # GET /product_types/new
  def new
    @product_type = ProductType.new
  end

  # GET /product_types/1/edit
  def edit
  end

  # POST /product_types or /product_types.json
  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to product_type_url(@product_type), notice: "Product type was successfully created." }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1 or /product_types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to product_type_url(@product_type), notice: "Product type was successfully updated." }
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1 or /product_types/1.json
  def destroy
    @product_type.destroy

    respond_to do |format|
      format.html { redirect_to product_types_url, notice: "Product type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_type_params
      params.require(:product_type).permit(:name)
    end
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/views/product_types/_form.html.haml
= form_for @product_type do |f|
  - if @product_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product_type.errors.count, "error")} prohibited this product_type from being saved:"
      %ul
        - @product_type.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/product_types/edit.html.haml
%h2 Editing Product Type

= render 'form'

app/views/product_types/index.html.haml
%h2 Product Types

%table
  %thead
    %tr
      %th Name
      %th
      %th

  %tbody
    - @product_types.each do |product_type|
      %tr
        %td= link_to product_type.name, product_type
        %td= link_to 'Edit', edit_product_type_path(product_type)
        %td= link_to 'Destroy', product_type, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Product Type', new_product_type_path

app/views/product_types/new.html.haml
%h2 New Product Type

= render 'form'

app/views/product_types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product_type.name

= link_to 'Edit', edit_product_type_path(@product_type)