config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :product_types
  resources :products
  resources :notes
  resources :note_categories
  resources :brands

  root 'static_pages#home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id               :integer          not null, primary key
#  name             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  note_category_id :integer          not null
#
# Indexes
#
#  index_notes_on_note_category_id  (note_category_id)
#
# Foreign Keys
#
#  note_category_id  (note_category_id => note_categories.id)
#
class Note < ApplicationRecord
  belongs_to :note_category
  
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :note_category_id, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_url, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to notes_url notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:name, :note_category_id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
= form_for @note do |f|
  - if @note.errors.any?
    #error_explanation
      %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      %ul
        - @note.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :note_category_id
    = f.collection_select :note_category_id, NoteCategory.all, :id, :name
  .actions
    = f.submit 'Save'

app/views/notes/edit.html.haml
%h2 Editing Note

= render 'form'

app/views/notes/index.html.haml
%h2 Notes

%table
  %thead
    %tr
      %th Name
      %th Note category
      %th
      %th

  %tbody
    - @notes.each do |note|
      %tr
        %td= link_to note.name, note
        %td= note.note_category.name
        %td= link_to 'Edit', edit_note_path(note)
        %td= link_to 'Delete', note, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Note', new_note_path

app/views/notes/new.html.haml
%h2 New Note

= render 'form'

app/views/notes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @note.name
%p
  %b Note category:
  = @note.note_category.name

= link_to 'Edit', edit_note_path(@note)