config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :product_types
  resources :products
  resources :notes
  resources :note_categories
  resources :brands

  root 'static_pages#home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/brand.rb
# == Schema Information
#
# Table name: brands
#
#  id         :integer          not null, primary key
#  name       :string
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Brand < ApplicationRecord
	has_many :products

	validates :name, presence: true
	validates :url, presence: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: %i[ show edit update destroy ]

  # GET /brands or /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1 or /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands or /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully created." }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1 or /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully updated." }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1 or /brands/1.json
  def destroy
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url, notice: "Brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:name, :url)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_brand.haml
%dl
  %dt= link_to brand.name, brand
  %dd= brand.url

app/views/brands/_form.haml
= form_with(model: brand) do |form|
  - if brand.errors.any?
    %div{style: "color: red"}
      %h2
        = pluralize(brand.errors.count, "error")
        prohibited this brand from being saved:
      %ul
        - brand.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :name, style: "display: block"
    = form.text_field :name
  %div
    = form.label :url, style: "display: block"
    = form.text_field :url
  %div
    = form.submit

app/views/brands/_form.html.haml
= form_for @brand do |f|
  - if @brand.errors.any?
    #error_explanation
      %h2= "#{pluralize(@brand.errors.count, "error")} prohibited this brand from being saved:"
      %ul
        - @brand.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/brands/edit.haml
%h1 Editing brand
= render "form", brand: @brand
%br/
%div
  = link_to "Show this brand", @brand
  |
  \#{link_to "Back to brands", brands_path}

app/views/brands/edit.html.haml
%h2 Editing Brand

= render 'form'

app/views/brands/index.haml
%p{style: "color: green"}= notice
%h2 Brands
#brands
  - @brands.each do |brand|
    = render brand

= link_to "New brand", new_brand_path

app/views/brands/index.html.haml
%h2 Brands

%table
  %thead
    %tr
      %th Name
      %th Url
      %th
      %th

  %tbody
    - @brands.each do |brand|
      %tr
        %td= link_to brand.name, brand
        %td= brand.url
        %td= link_to 'Edit', edit_brand_path(brand)
        %td= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Brand', new_brand_path

app/views/brands/new.haml
%h1 New brand
= render "form", brand: @brand
%br/
%div
  = link_to "Back to brands", brands_path

app/views/brands/new.html.haml
%h2 New Brand

= render 'form'

app/views/brands/show.haml
%p{style: "color: green"}= notice
= render @brand
%div
  = link_to "Edit this brand", edit_brand_path(@brand)
  |
  \#{link_to "Back to brands", brands_path}#{button_to "Destroy this brand", @brand, method: :delete}

app/views/brands/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @brand.name
%p
  %b Url:
  = @brand.url

= link_to 'Edit', edit_brand_path(@brand)