config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :product_types
  resources :products
  resources :notes
  resources :note_categories
  resources :brands

  root 'static_pages#home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id              :integer          not null, primary key
#  description     :string
#  ingredients     :string
#  name            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  brand_id        :integer          not null
#  product_type_id :integer          not null
#
# Indexes
#
#  index_products_on_brand_id         (brand_id)
#  index_products_on_product_type_id  (product_type_id)
#
# Foreign Keys
#
#  brand_id         (brand_id => brands.id)
#  product_type_id  (product_type_id => product_types.id)
#
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :product_type

  validates :name, presence: true
  validates :description, presence: true
  validates :ingredients, presence: true
  validates :brand_id, presence: true
  validates :product_type_id, presence: true
end

app/models/product_type.rb
# == Schema Information
#
# Table name: product_types
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class ProductType < ApplicationRecord
	has_many :products

	validates :name, presence: true
	validates :name, uniqueness: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :ingredients, :brand_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :ingredients
    = f.text_field :ingredients
  .field
    = f.label :brand
    = f.text_field :brand
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h2 Editing Product

= render 'form'

app/views/products/index.html.haml
%h2 Products

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Ingredients
      %th Brand
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.name, product
        %td= product.description
        %td= product.ingredients
        %td= product.brand
        %td= link_to 'Edit', edit_product_path(product)
        %td= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h2 New Product

= render 'form'

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b Description:
  = @product.description
%p
  %b Ingredients:
  = @product.ingredients
%p
  %b Brand:
  = @product.brand

= link_to 'Edit', edit_product_path(@product)